#ifndef SHADER_RECOMPILIER_RDNADECODER_RDNAOPCODE_HPP
#define SHADER_RECOMPILIER_RDNADECODER_RDNAOPCODE_HPP

#include <cstdint>

namespace ShaderRecompiler {

enum class RdnaOpcode : std::uint16_t {
    Invalid,
    SMovB32,
    SMovB64,
    SMovkI32,
    SAddI32,
    SAddU32,
    SSubI32,
    SSubU32,
    SMulI32,
    SAndB32,
    SOrB32,
    SXorB32,
    SLshlB32,
    SLshrB32,
    SAshrI32,
    SBfeU32,
    SBfeI32,
    SCmpEqI32,
    SCmpLtI32,
    SCmpGtI32,
    SCmpEqU32,
    SCbranchScc0,
    SCbranchScc1,
    SCbranchVccz,
    SCbranchVccnz,
    SCbranchExecz,
    SCbranchExecnz,
    SBranch,
    SSetpcB64,
    SEndpgm,
    SWaitcnt,
    SBarrier,
    SNop,
    SLoadDword,
    SLoadDwordx2,
    SLoadDwordx4,
    SLoadDwordx8,
    SLoadDwordx16,
    VMovB32,
    VAddF32,
    VSubF32,
    VMulF32,
    VMadF32,
    VFmaF32,
    VAddI32,
    VSubI32,
    VMulLoU32,
    VMulHiU32,
    VMadU64U32,
    VSadU32,
    VAndB32,
    VOrB32,
    VXorB32,
    VLshlB32,
    VLshrB32,
    VAshrI32,
    VCmpEqF32,
    VCmpLtF32,
    VCmpGtF32,
    VCndmaskB32,
    VCvtF32I32,
    VCvtI32F32,
    VCvtF32U32,
    VCvtU32F32,
    VCvtF32F16,
    VCvtF16F32,
    VRcpF32,
    VRsqF32,
    VSqrtF32,
    VExpF32,
    VLogF32,
    VSinF32,
    VCosF32,
    VFloorF32,
    VCeilF32,
    VFractF32,
    VMinF32,
    VMaxF32,
    VMinI32,
    VMaxI32,
    VReadfirstlaneB32,
    VReadlaneB32,
    VWritelaneB32,
    VMovreldB32,
    BufferLoadFormatX,
    BufferLoadFormatXy,
    BufferLoadFormatXyz,
    BufferLoadFormatXyzw,
    BufferLoadDword,
    BufferLoadDwordx2,
    BufferLoadDwordx4,
    BufferStoreFormatX,
    BufferStoreDword,
    BufferStoreDwordx4,
    TBufferLoadFormatX,
    TBufferLoadFormatXyzw,
    ImageSample,
    ImageSampleLz,
    ImageLoad,
    ImageStore,
    ImageGetResinfo,
    DsRead2B32,
    DsWrite2B32,
    ExpMrt,
    ExpPos,
    ExpParam
};

[[nodiscard]] bool IsScalarAluOpcode(RdnaOpcode opcode);
[[nodiscard]] bool IsVectorAluOpcode(RdnaOpcode opcode);
[[nodiscard]] bool IsBranchOpcode(RdnaOpcode opcode);
[[nodiscard]] bool IsScalarMemoryOpcode(RdnaOpcode opcode);
[[nodiscard]] bool IsBufferMemoryOpcode(RdnaOpcode opcode);
[[nodiscard]] bool IsImageOpcode(RdnaOpcode opcode);
[[nodiscard]] bool IsExportOpcode(RdnaOpcode opcode);

}

#endif
